server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost;instanceName=TESTDEVELOPMENT;databaseName=FERREMAX2;encrypt=false
    username: sa
    password: Exitus2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: student-group
    auto-offset-reset: earliest
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

redis:
  host: localhost
  port: 6379
  database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
